esphome:
  name: ${node_name}
  platformio_options:
    board_build.f_cpu: 160000000L
    board_build.f_flash: 80000000L
    board_build.flash_size: 4MB

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y
      CONFIG_ESPTOOLPY_HEADER_FLASHSIZE_UPDATE: "n"

# Enable logging with INFO level
logger:
  level: INFO
  baud_rate: 0  # Disable UART logging to prevent interference

# Enable Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}

ota:
  platform: esphome  # Required for ESPHome 2023.6.0 and above
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: "${room_name} Node Hotspot"
    password: !secret wifi_password

# Web server for monitoring
web_server:
  port: 80

# Enable mDNS
mdns:
  disabled: False

# Captive portal in case of connection issues
captive_portal:

# Output for Status LED
output:
  - platform: gpio
    pin: ${status_led_gpio}
    inverted: true
    id: status_led

# Script for Flashing the LED When Motion is Detected
script:
  - id: flash_led_script
    mode: restart
    then:
      - repeat:
          count: 3  # Number of flashes (adjust as needed)
          then:
            - output.turn_on: status_led
            - delay: 500ms
            - output.turn_off: status_led
            - delay: 500ms

# Interval to Check Wi-Fi Connection and Blink LED if Disconnected
interval:
  - interval: 2s
    then:
      - if:
          condition:
            not:
              wifi.connected: {}
          then:
            - output.turn_on: status_led
            - delay: 1s
            - output.turn_off: status_led
            - delay: 1s

# Binary Sensors for Presence Detection and Radar
binary_sensor:
  # Presence Detection via GPIO
  - platform: gpio
    pin: ${presence_gpio}
    name: "${room_name} Presence"
    device_class: presence

  # Radar Binary Sensors
  - platform: ld2410
    has_target:
      name: "${room_name} Radar - Presence Detected"
      id: radar_has_target
      on_press:
        then:
          - script.execute: flash_led_script
    has_moving_target:
      name: "${room_name} Radar - Movement Detected"
      id: radar_moving_target
    has_still_target:
      name: "${room_name} Radar - Stillness Detected"
      id: radar_still_target

# Sensors for Radar and Environment
sensor:
  # Radar Sensors
  - platform: ld2410
    moving_distance:
      name: "${room_name} Radar - Moving Target Distance"
      id: radar_moving_distance
      unit_of_measurement: "cm"
      device_class: distance
    still_distance:
      name: "${room_name} Radar - Still Target Distance"
      id: radar_still_distance
      unit_of_measurement: "cm"
      device_class: distance
    moving_energy:
      name: "${room_name} Radar - Moving Target Energy"
      unit_of_measurement: "%"
      device_class: power
    still_energy:
      name: "${room_name} Radar - Still Target Energy"
      unit_of_measurement: "%"
      device_class: power
    detection_distance:
      name: "${room_name} Radar - Detection Distance"
      id: radar_detection_distance
      unit_of_measurement: "cm"
      device_class: distance
    g0:
      move_energy:
        name: "${room_name} Radar - Gate 0 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 0 Still Energy"
    g1:
      move_energy:
        name: "${room_name} Radar - Gate 1 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 1 Still Energy"
    g2:
      move_energy:
        name: "${room_name} Radar - Gate 2 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 2 Still Energy"
    g3:
      move_energy:
        name: "${room_name} Radar - Gate 3 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 3 Still Energy"
    g4:
      move_energy:
        name: "${room_name} Radar - Gate 4 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 4 Still Energy"
    g5:
      move_energy:
        name: "${room_name} Radar - Gate 5 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 5 Still Energy"
    g6:
      move_energy:
        name: "${room_name} Radar - Gate 6 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 6 Still Energy"
    g7:
      move_energy:
        name: "${room_name} Radar - Gate 7 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 7 Still Energy"
    g8:
      move_energy:
        name: "${room_name} Radar - Gate 8 Move Energy"
      still_energy:
        name: "${room_name} Radar - Gate 8 Still Energy"

  # Temperature and Humidity Sensors
  - platform: dht
    pin: GPIO18  # Adjust if necessary
    model: AM2302
    temperature:
      name: "${room_name} Temperature"
      id: Temperature
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 1
            send_first_at: 1
        - lambda: |-
            if (x < -40 || x > 80) {
              ESP_LOGD("Temperature", "Rejected out of range value: %.1f", x);
              return {};
            } else {
              return x;
            }
    humidity:
      name: "${room_name} Humidity"
      id: Humidity
    update_interval: 30s

  # Template Sensor for Apparent Temperature
  - platform: template
    name: "${room_name} Apparent Temperature"
    unit_of_measurement: '°C'
    update_interval: 30s
    lambda: |-
      float T = id(Temperature).state;
      float RH = id(Humidity).state;
      ESP_LOGD("Apparent Temperature", "Temperature: %.2f, Humidity: %.2f", T, RH);
      if (T < -40 || T > 80 || RH < 0 || RH > 100) {
        ESP_LOGD("Apparent Temperature", "Rejected out of range values: T: %.2f, RH: %.2f", T, RH);
        return {};
      }
      float alpha = log(RH/100) + ((17.27 * T) / (237.7 + T));
      float Td = (237.7 * alpha) / (17.27 - alpha);
      float H = T + 0.5555 * (6.11 * exp((5417.7530 * ((1/273.16) - (1/(273.15 + Td))))) - 10);
      if (H < -40 || H > 80) {
        ESP_LOGD("Apparent Temperature", "Calculated out of range apparent temperature: %.2f", H);
        return {};
      }
      ESP_LOGD("Apparent Temperature", "Calculated apparent temperature: %.2f", H);
      return H;

# Number Components for LD2410 Parameters
number:
  - platform: ld2410
    g0:
      move_threshold:
        name: "${room_name} Radar - Gate 0 Move Threshold"
        id: g0_move_threshold
      still_threshold:
        name: "${room_name} Radar - Gate 0 Still Threshold"
        id: g0_still_threshold
  # Repeat for gates g1 to g8 as in your original configuration...

# Switch Component for Engineering Mode
switch:
  - platform: ld2410
    engineering_mode:
      name: "${room_name} Radar Engineering Mode"
      id: engineering_mode_switch
      restore_mode: ALWAYS_ON

# Select Components for LD2410 Configuration
select:
  - platform: ld2410
    distance_resolution:
      name: "${room_name} Radar - Distance Resolution"
  - platform: ld2410
    baud_rate:
      name: "${room_name} Radar - UART Baud Rate"
  - platform: ld2410
    light_function:
      name: "${room_name} Radar - Light Function"
  - platform: ld2410
    out_pin_level:
      name: "${room_name} Radar - OUT Pin Level"

# Button Components for LD2410 Actions
button:
  - platform: ld2410
    factory_reset:
      name: "${room_name} Radar Factory Reset"
  - platform: ld2410
    restart:
      name: "${room_name} Radar Restart"
  - platform: ld2410
    query_params:
      name: "${room_name} Radar Query Parameters"

# Text Sensors for Additional Information
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${room_name} Node IP Address"
  - platform: ld2410
    version:
      name: "${room_name} Radar Firmware Version"
    mac_address:
      name: "${room_name} Radar MAC Address"

# Configuration for the 24GHz mmWave XIAO Radar
ld2410:
  id: ld2410_radar
  throttle: 1000ms

# UART configuration with adjusted pins for LD2410 Radar
uart:
  id: ld2410_uart
  rx_pin: ${uart_rx_pin}
  tx_pin: ${uart_tx_pin}
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
