substitutions:
  node_name: "kitchen-node-v2-xiao"
  room_name: "Kitchen"
  api_encryption_key: !secret kitchennode_v2_key
  status_led_gpio: GPIO0
  presence_gpio: GPIO15
  uart_rx_pin: GPIO2
  uart_tx_pin: GPIO21

<<: !include common-node-config.yaml
