esphome:
  name: bathroom_node_v2
  platform: ESP32
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.0
    platform_version: https://github.com/stintel/platform-espressif32#esp32-c6-test

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

api:
  encryption:
    key: !secret bathroomnode_v2_key

web_server:
  port: 80

sensor:
  - platform: gpio
    pin: GPIO4
    name: "Presence Sensor"
    update_interval: 1s

logger:
  level: DEBUG
