substitutions:
  node_name: "bedroom-node-v2"
  room_name: "Bedroom"
  api_encryption_key: !secret bedroomnode_v2_key
  status_led_gpio: GPIO14
  presence_gpio: GPIO13
  uart_rx_pin: GPIO2
  uart_tx_pin: GPIO21
  dht_sensor_gpio: GPIO17

# Enable logging with INFO level
logger:
  level: INFO
  baud_rate: 0  # Disable UART logging to prevent interference

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.1.138

text_sensor:
  - platform: template
    name: "Bedroom Node Note"
    lambda: |-
      return esphome::optional<std::string>("Note: This node does not plug into USB for some reason.");
    update_interval: never

<<: !include common-node-config.yaml
